# =============================================================================
# PREPARE DATA
# =============================================================================

prepare_data:
  input_output_data:
    file_path: data/input_output_data.csv

  # Possible values: 1/4 and 1/8
  symmetry: 1/4

  # Possible outputs:
  # - keff_start
  # - keff_max
  # - ppf_start
  # - ppf_max
  # - ppf_end
  # - cycle_length_in_days
  output_cols: &output_cols
    - keff_start
    - keff_max
    - ppf_start
    - ppf_max
    - ppf_end
    - cycle_length_in_days


# =============================================================================
# USING MONOCORES DICTIONARY
# =============================================================================

use_monocores:
  execute: True

  monocre_data:
    file_path: data/monocores_dictionary.xlsx
    sheet_name: summary

  core_number_column: monocore

  # Possible transform colum names:
  # - cycle_length_in_days
  # - keff_max
  # - Pxy_max
  # - Pz_max
  # - keff_start
  # - PPF_start
  # - PPF_max
  # - PPF_end
  transform_col_names:
    - cycle_length_in_days
    - keff_max
    - Pxy_max
    - Pz_max
    - keff_start
    - PPF_start
    - PPF_max
    - PPF_end


# =============================================================================
# MODELING
# =============================================================================

modeling:
  data:
    test_size: 0.2
    random_state: 42

  neural_network:
    layers:
      layer1:
        neurons: 50
        activation: linear

      layer2:
        neurons: 50
        activation: linear

      layer_output:
        activation: linear

    loss_function: mean_squared_error
    optimizer: adam

    epochs: 200


# =============================================================================
# EVALUATION OF THE MODEL
# =============================================================================

evaluate:
  output_cols: *output_cols
  metrics:
    - mean_absolute_error
    - mean_realative_error

# Reaktywność: 1 - 1/keff